apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mywebsite-ui
  template:
    metadata:
      labels:
        app: mywebsite-ui
    spec:
      containers:
      - image: chrislprice/harnesstestlab:latest
        name: mywebsite-ui
        ports:
        - containerPort: 80

      